src/main/java/xjt/demo/common/enumeration/entity/GroupType.java
package xjt.demo.common.enumeration.entity;

/**
 * 组类型
 * 
 * 机构类型 = Organization,
 * 部门类型 = Department,
 * 角色组 = RoleGorup,
 * 
 * @author vincent
 *
 */
public enum GroupType {

	/**
	 * 机构类型
	 */
	Organization("01","机构"),
	/**
	 * 部门类型 
	 */
	Department("02","部门"),
	/**
	 * 角色组类型
	 */
	RoleGorup("03","角色组");
	
	private GroupType(String value,String name) {
		this.value = value;
		this.name = name;
	}
	
	private String value;
	
	private String name;

	/**
	 * 获取类型值
	 * 
	 * @return String
	 */
	public String getValue() {
		return value;
	}

	/**
	 * 获取类型名称
	 * 
	 * @return String
	 */
	public String getName() {
		return name;
	}
}

src/main/java/xjt/demo/entity/account/Group.java
package xjt.demo.entity.account;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;


import xjt.common.utils.CollectionUtils;
import xjt.demo.common.SystemVariableUtils;
import xjt.demo.common.enumeration.SystemDictionaryCode;
import xjt.demo.common.enumeration.entity.GroupType;
import xjt.demo.entity.UniversallyUniqueIdentifier;

/**
 * 组实体
 * 
 * @author vincent
 *
 */
@Entity
@Table(name="TB_GROUP")
@SuppressWarnings("serial")
public class Group extends UniversallyUniqueIdentifier{

	public static final String UserGroups = "userGroups";
	
	//名称
	private String name;
	//成员
	private List<User> membersList = new ArrayList<User>();
	//上级组
	private Group parent;
	//下级组集合
	private List<Group> children = new ArrayList<Group>();
	//类型
	private String type;
	//备注
	private String remark;
	//状态
	private int state;
	//拥有资源
	private List<Resource> resourcesList = new ArrayList<Resource>();
	//shiro role 字符串
	private String role;
	//shiro role连定义的值
	private String value;
	
	/**
	 * 构造方法
	 */
	public Group() {
		
	}

	/**
	 * 获取组名称
	 * 
	 * @return String
	 */
	@Column(length=64,nullable=false,unique=true)
	public String getName() {
		return name;
	}

	/**
	 * 设置组名称
	 * 
	 * @param name 组名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 获取上级组
	 * 
	 * @return {@link Group}
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "FK_PARENT_ID")
	public Group getParent() {
		return parent;
	}

	/**
	 * 设置上级组
	 * 
	 * @param parent 组实体
	 */
	public void setParent(Group parent) {
		this.parent = parent;
	}

	/**
	 * 获取下级组集合
	 * 
	 * @return List
	 */
	@OneToMany(fetch=FetchType.LAZY,mappedBy="parent",cascade={CascadeType.ALL})
	public List<Group> getChildren() {
		
		return children;
	}

	/**
	 * 设置下级组集合
	 * 
	 * @param children 下级组集合
	 */
	public void setChildren(List<Group> children) {
		this.children = children;
	}
	
	/**
	 * 获取组成员
	 * 
	 * @return List
	 */
	@ManyToMany(fetch=FetchType.LAZY)
	@JoinTable(name = "TB_GROUP_USER", joinColumns = { @JoinColumn(name = "FK_GROUP_ID") }, inverseJoinColumns = { @JoinColumn(name = "FK_USER_ID") })
	public List<User> getMembersList() {
		return membersList;
	}

	/**
	 * 设置组成员
	 * 
	 * @param membersList 用户集合
	 */
	public void setMembersList(List<User> membersList) {
		this.membersList = membersList;
	}

	/**
	 * 获取拥有资源
	 * 
	 * @return List
	 */
	@ManyToMany(fetch=FetchType.LAZY)
	@JoinTable(name = "TB_GROUP_RESOURCE", joinColumns = { @JoinColumn(name = "FK_GROUP_ID") }, inverseJoinColumns = { @JoinColumn(name = "FK_RESOURCE_ID") })
	public List<Resource> getResourcesList() {
		return resourcesList;
	}

	/**
	 * 设置该组的操作资源
	 * 
	 * @param resourcesList 资源集合
	 */
	public void setResourcesList(List<Resource> resourcesList) {
		this.resourcesList = resourcesList;
	}

	/**
	 * 获取组类型
	 * 
	 * @return String
	 */
	@Column(nullable=false,length=2)
	public String getType() {
		return type;
	}

	/**
	 * 设置组类型
	 * 
	 * @param type 类型
	 * 
	 * @see GroupType
	 */
	public void setType(String type) {
		this.type = type;
	}
	
	/**
	 * 获取备注
	 * 
	 * @return String
	 */
	@Column(columnDefinition="text")
	public String getRemark() {
		return remark;
	}

	/**
	 * 设置备注
	 * 
	 * @param remark 备注
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	/**
	 * 获取组状态
	 * @return
	 */
	@Column(nullable=false)
	public int getState() {
		return state;
	}

	/**
	 * 设置组状态
	 * @param state
	 */
	public void setState(int state) {
		this.state = state;
	}

	/**
	 * 获取所有成员的id
	 * 
	 * @return List
	 */
	@Transient
	public List<String> getMemberIds() {
		return CollectionUtils.extractToList(this.membersList, "id");
	}
	
	/**
	 * 获取当前实体是否是为根节点,如果是返回ture，否则返回false
	 * 
	 * @return boolean
	 */
	@Transient
	public boolean getLeaf() {
		return this.children != null && children.size() > 0;
		
	}
	
	/**
	 * 获取shiro role字符串
	 * @return String
	 */
	@Column(unique=true,length=64)
	public String getRole() {
		return role;
	}

	/**
	 * 设置shiro role字符串
	 * @param role字符串
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * 获取shiro role连定义的值
	 * @return String
	 */
	@Column(length=512)
	public String getValue() {
		return value;
	}

	/**
	 * 设置 shiro role连定义的值
	 * @param value 值
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * 获取父类ID
	 * 
	 * @return String
	 */
	@Transient
	public String getParentId() {
		
		return this.parent == null ? "" : this.parent.getId();
	}
	
	/**
	 * 获取父类名称
	 * 
	 * @return String
	 */
	@Transient
	public String getParentName(){
		return this.parent == null ? "" : this.parent.getName();
	}
	
	/**
	 * 获取状态名称
	 * 
	 * @return String
	 */
	@Transient
	public String getStateName() {
		return SystemVariableUtils.getDictionaryNameByValue(SystemDictionaryCode.State, this.state);
	}
}

src/main/java/xjt/demo/entity/account/User.java
package xjt.demo.entity.account;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;


import xjt.common.utils.CollectionUtils;
import xjt.demo.common.SystemVariableUtils;
import xjt.demo.common.enumeration.SystemDictionaryCode;
import xjt.demo.common.enumeration.entity.State;
import xjt.demo.entity.UniversallyUniqueIdentifier;

/**
 * 用户类
 * @author vincent
 *
 */
@Entity
@Table(name="TB_USER")
@SuppressWarnings("serial")
public class User extends UniversallyUniqueIdentifier{
	
	//登录名称
	private String username;
	//登录密码
	private String password;
	//真实名称
	private String realname;
	//状态 
	private Integer state;
	//邮件
	private String email;
	//用户所在的组
	private List<Group> groupsList = new ArrayList<Group>();
	
	/**
	 * 构造方法
	 */
	public User() {
	}
	
	/**
	 * 获取登录名称
	 * 
	 * @return String
	 */
	@Column(length=64,unique=true,nullable=false,updatable=false)
	public String getUsername() {
		return username;
	}

	/**
	 * 设置登录名称
	 * 
	 * @param username 登录名称
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * 获取登录密码
	 * 
	 * @return String
	 */
	@Column(nullable=false,length=32,updatable=false)
	public String getPassword() {
		return password;
	}

	/**
	 * 设置登录密码
	 * 
	 * @param password 登录密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * 获取真实姓名
	 * 
	 * @return String
	 */
	@Column(length=128,nullable=false)
	public String getRealname() {
		return realname;
	}

	/**
	 * 设置真实名称
	 * 
	 * @param realName 真实姓名
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}


	/**
	 * 获取用户状态
	 * 
	 * @return {@link State}
	 */
	@Column(nullable=false)
	public Integer getState() {
		return state;
	}

	/**
	 * 设置用户状态
	 * 
	 * @param state 用户状态
	 */
	public void setState(Integer state) {
		this.state = state;
	}
	
	/**
	 * 获取邮件
	 * @return String
	 */
	@Column(length=256)
	public String getEmail() {
		return email;
	}

	/**
	 * 设置邮件 
	 * @param email 邮件地址 
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	
	/**
	 * 获取该用户所在的组
	 * 
	 * @return List
	 */
	@ManyToMany(fetch=FetchType.LAZY)
	@JoinTable(name = "TB_GROUP_USER", joinColumns = { @JoinColumn(name = "FK_USER_ID") }, inverseJoinColumns = { @JoinColumn(name = "FK_GROUP_ID") })
	public List<Group> getGroupsList() {
		return groupsList;
	}
	
	/**
	 * 设置用户所在的组
	 * 
	 * @param groupsList 组集合
	 */
	public void setGroupsList(List<Group> groupsList) {
		this.groupsList = groupsList;
	}
	
	/**
	 * 获取状态名称
	 * 
	 * @return String
	 */
	@Transient
	public String getStateName() {
		return SystemVariableUtils.getDictionaryNameByValue(SystemDictionaryCode.State, this.state);
	}
	
	/**
	 * 获取所在组所用名称
	 * 
	 * @return String
	 */
	@Transient
	public String getGroupNames() {
		return CollectionUtils.extractToString(this.groupsList, "name", ",");
	}

	
	public String toString() {
		return username;
	}
}

src/main/java/xjt/demo/web/account/GroupController.java
package xjt.demo.web.account;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.data.web.PageableDefaults;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import xjt.common.orm.core.PropertyFilter;
import xjt.common.orm.core.PropertyFilters;
import xjt.common.utils.ServletUtils;
import xjt.demo.common.SystemVariableUtils;
import xjt.demo.common.enumeration.SystemDictionaryCode;
import xjt.demo.common.enumeration.entity.GroupType;
import xjt.demo.entity.account.Group;
import xjt.demo.service.account.AccountManager;

/**
 * 组管理Controller
 * 
 * @author vincent
 *
 */
@Controller
@RequestMapping("/account/group")
public class GroupController {
	
	@Autowired
	private AccountManager accountManager;
	
	/**
	 * 获取资源列表
	 * 
	 * @param pageRequest 分页实体信息
	 * @param request HttpServlet请求
	 * 
	 * @return {@link Page}
	 */
	@RequestMapping("view")
	public Page<Group> view(
			@PageableDefaults(sort = { "id" }, sortDir = Direction.DESC) Pageable pageable,
			HttpServletRequest request) {
		
		List<PropertyFilter> filters = PropertyFilters.build(request);
		
		request.setAttribute("states", SystemVariableUtils.getDataDictionariesByCategoryCode(SystemDictionaryCode.State,"3"));
		request.setAttribute("groupsList", accountManager.getAllGroup(GroupType.RoleGorup));
		
		filters.add(PropertyFilters.build("EQS_type", GroupType.RoleGorup.getValue()));
		
		return accountManager.searchGroupPage(pageable, filters);
	}
	
	/**
	 * 
	 * 保存资源，保存成功后重定向到:account/group/view
	 * 
	 * @param entity 实体信息
	 * @param request HttpServlet请求,由于保存时候需要到parentId和resourceIds的参数，为了简洁，直接使用request,不用@RequestParam获取参数
	 * @param redirectAttributes spring mvc 重定向属性
	 * 
	 * @return String
	 */
	@RequestMapping("save")
	public String save(@ModelAttribute("entity") Group entity,HttpServletRequest request,RedirectAttributes redirectAttributes) {
		
		String parentId = request.getParameter("parentId");
		
		if (StringUtils.isEmpty(parentId)) {
			entity.setParent(null);
		} else {
			entity.setParent(accountManager.getGroup(parentId));
		}
		
		List<String> resourceIds = ServletUtils.getParameterValues(request, "resourceIds");
		
		entity.setResourcesList(accountManager.getResources(resourceIds));
		
		accountManager.saveGroup(entity);
		redirectAttributes.addFlashAttribute("message", "保存成功");
		return "redirect:/account/group/view";
	}
	
	/**
	 * 
	 * 读取资源信息
	 * 
	 * @param model Spring mvc的Model接口，主要是将model的属性返回到页面中
	 * 
	 */
	@RequestMapping("read")
	public String read(@RequestParam(value = "id", required = false)String id,Model model) {
		
		model.addAttribute("resourcesList", accountManager.getAllResources());
		model.addAttribute("states", SystemVariableUtils.getDataDictionariesByCategoryCode(SystemDictionaryCode.State,"3"));
		
		if (StringUtils.isEmpty(id)) {
			model.addAttribute("groupsList", accountManager.getAllGroup(GroupType.RoleGorup));
		} else {
			model.addAttribute("groupsList", accountManager.getAllGroup(GroupType.RoleGorup,id));
		}
		
		return "account/group/read";
	}
	
	/**
	 * 删除资源
	 */
	@RequestMapping("delete")
	public String delete(@RequestParam("ids")List<String> ids,RedirectAttributes redirectAttributes) {
		accountManager.deleteGroups(ids);
		redirectAttributes.addFlashAttribute("message", "删除" + ids.size() + "条信息成功");
		return "redirect:/account/group/view";
	}
	
	/**
	 * 绑定实体数据，如果存在id时获取后从数据库获取记录，进入到相对的C后在将数据库获取的记录填充到相应的参数中
	 * 
	 * @param id 主键ID
	 * 
	 */
	@ModelAttribute("entity")
	public Group bindingModel(@RequestParam(value = "id", required = false)String id) {
		
		Group group = new Group();
		
		if (StringUtils.isNotEmpty(id)) {
			group = accountManager.getGroup(id);
		}
		
		return group;
	}
}

src/main/java/xjt/demo/web/account/ResourceController.java
package xjt.demo.web.account;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.data.web.PageableDefaults;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import xjt.common.orm.core.PropertyFilter;
import xjt.common.orm.core.PropertyFilters;
import xjt.demo.common.SystemVariableUtils;
import xjt.demo.common.enumeration.SystemDictionaryCode;
import xjt.demo.entity.account.Resource;
import xjt.demo.service.account.AccountManager;

/**
 * 资源管理Controller
 * 
 * @author vincent
 *
 */
@Controller
@RequestMapping("/account/resource")
public class ResourceController {

	@Autowired
	private AccountManager accountManager;
	
	/**
	 * 获取资源列表
	 * 
	 * @param pageRequest 分页实体信息
	 * @param request HttpServlet请求
	 * 
	 * @return {@link Page}
	 */
	@RequestMapping("view")
	public Page<Resource> view(
			@PageableDefaults(sort = {"id"},sortDir=Direction.DESC)Pageable pageable,
			HttpServletRequest request) {
		
		List<PropertyFilter> filters = PropertyFilters.build(request);
		
		request.setAttribute("resourceType", SystemVariableUtils.getDataDictionariesByCategoryCode(SystemDictionaryCode.ResourceType));
		request.setAttribute("resourcesList", accountManager.getAllResources());
		
		return accountManager.searchResourcePage(pageable, filters);
	}
	
	/**
	 * 
	 * 保存资源,保存成功后重定向到:account/resource/view
	 * 
	 * @param entity 实体信息
	 * @param parentId 所对应的父类id
	 * @param redirectAttributes spring mvc 重定向属性
	 * 
	 * @return String
	 */
	@RequestMapping("save")
	public String save(@ModelAttribute("entity") Resource entity,String parentId,RedirectAttributes redirectAttributes) {
		
		if (StringUtils.isEmpty(parentId)) {
			entity.setParent(null);
		} else {
			entity.setParent(accountManager.getResource(parentId));
		}
		
		accountManager.saveResource(entity);
		redirectAttributes.addFlashAttribute("message", "保存成功");
		return "redirect:/account/resource/view";
	}
	
	/**
	 * 
	 * 读取资源信息,返回account/resource/read.ftl页面
	 * 
	 * @param model Spring mvc的Model接口，主要是将model的属性返回到页面中
	 * 
	 * @return String
	 */
	@RequestMapping("read")
	public String read(@RequestParam(value = "id", required = false)String id,Model model) {
		
		model.addAttribute("resourceType", SystemVariableUtils.getDataDictionariesByCategoryCode(SystemDictionaryCode.ResourceType));

		if (StringUtils.isEmpty(id)) {
			model.addAttribute("resourcesList", accountManager.getAllResources());
		} else {
			model.addAttribute("resourcesList", accountManager.getAllResources(id));
		}
		
		return "account/resource/read";
	}
	
	/**
	 * 通过主键id集合删除资源,删除成功后重定向到:account/resource/view
	 * 
	 * @param ids 主键id集合
	 * @param redirectAttributes spring mvc 重定向属性
	 * 
	 * @return String
	 */
	@RequestMapping("delete")
	public String delete(@RequestParam("ids")List<String> ids,RedirectAttributes redirectAttributes) {
		accountManager.deleteResources(ids);
		redirectAttributes.addFlashAttribute("message", "删除" + ids.size() + "条信息成功");
		return "redirect:/account/resource/view";
	}
	
	/**
	 * 绑定实体数据，如果存在id时获取后从数据库获取记录，进入到相对的C后在将数据库获取的记录填充到相应的参数中
	 * 
	 * @param id 主键ID
	 * 
	 */
	@ModelAttribute("entity")
	public Resource bindingModel(@RequestParam(value = "id", required = false)String id) {
		
		Resource resource = new Resource();
		
		if (StringUtils.isNotEmpty(id)) {
			resource = accountManager.getResource(id);
		}
		
		return resource;
	}
}

src/main/webapp/WEB-INF/page/account/group/read.ftl
<div id="edit_form" class="form_widget">
	<form id="group_form" action="account/group/save" method="post">
		<input type="hidden" name="id" value="${entity.id!""}" />
		<input type="hidden" name="type" value="03" />
	    <div class="column">
	        <label for="name">
				组名称:
	        </label>
	        <div class="field">
	            <input type="text" id="name" name="name" class="text_input_big required" size="25" value="${entity.name!""}"/>
	        </div>
	        <label for="state">
				状态:
	        </label>
	        <div class="field">
	           <select class="selection" name="state" id="state" size="25">
	           		<#list states as s>
		           		<option value="${s.value}" <#if entity.state == s.value?number >selected="selected"</#if> >
							${s.name}
		                </option>
	           		</#list>
	           </select>
	         </div>
	    </div>
	    <div class="column">
	    	<label for="parentId">
	    		所属父类:
	    	</label>
	    	<div class="field">
	    		<select class="selection" height="150" search="true" name="parentId" id="parentId" size="66">
	                <#list groupsList as gl>
	                	<option value="${gl.id}" <#if entity.parentId==gl.id> selected="selected" </#if> >${gl.name}</option>
	                </#list>
	           </select>
	    	</div>
	    </div>
	    <div class="column">
	    	<label for="resourceIds">
	    		拥有资源:
	    	</label>
	    	<div class="field">
	    		<select class="selection" height="150" multiple="multiple" search="true" name="resourceIds" id="resourceIds" size="66">
	                <#list resourcesList as rl>
	                	<#assign isSelected = false />
	                	<#list entity.resourcesList as erl>
	                		<#if erl.id == rl.id>
	                			<#assign isSelected = true />
	                			<#break />
	                		</#if>
	                	</#list>
	                	<option value="${rl.id}" <#if isSelected> selected="selected" </#if> >${rl.name}</option>
	                </#list>
	           </select>
	    	</div>
	    </div>
	    <div class="column">
	    	<label for="remark">
	    		备注:
	    	</label>
	    	<div class="field">
	    		<input type="text" id="icon" name="remark" class="text_input_big" size="66" value="${entity.remark!""}" />
	    	</div>
	    </div>
	</form>
	<div class="clear">
		<a href="javascript:$.form.resetForm('#group_form')" title="清空表单"><span class="button right">重 置</span></a>
		<a href="javascript:$.form.submitMaskForm('#group_form',{maskEl:'#edit_group',target:'#main_content'});" title="保存信息"><span class="button right">保 存</span></a>
	</div>
</div>

src/main/webapp/WEB-INF/page/account/group/view.ftl
<#assign shiro=JspTaglibs["/WEB-INF/taglib/shiro.tld"] />
<script>
	$(document).ready(function(){
		$(".close").click(
			function () {
				$(this).parent().fadeTo(400, 0, function () {
					$(this).slideUp(400);
				});
				return false;
			}
		);
		$("#selectAll").click(function(){
			var checks = $("#group_list tbody").find("input[type='checkbox'][id!='selectAll']");
			checks.attr('checked', $(this).is(':checked'));
			checks.click();
		});
	});
	
	function search(page){
		var param = $.form.getParameters("#search_form",true);
		param["page.size"] = $("#size").val();
		param["page.page"] = page || 0;
		$.maskLoad({
			url:'account/group/view',
			param:param,
			target:'#main_content'
		});
	}
</script>
<div id="group_panel">
	<div id="search_group_dailog">
		<form id="search_form" action="account/group/view" method="post">
			<div class="column">
		        <label for="filter_RLIKES_name">
					组名称:
		        </label>
		        <div class="field">
		            <input type="text" id="filter_RLIKES_name" name="filter_RLIKES_name" class="text_input_big" size="25" value="${RequestParameters.filter_RLIKES_name!""}"/>
		        </div>
		    </div>
		    <div class="column">
		        <label for="filter_EQS_state">
					状态:
		        </label>
		        <div class="field">
		            <select class="selection" name="filter_EQI_state" id="filter_EQI_state" size="25">
		           		<option value="">
							全部
		                </option>
		                <#list states as s>
			                <option value="${s.value}" <#if RequestParameters['filter_EQI_state']?has_content && RequestParameters['filter_EQI_state'] ==s.value >selected="selected"</#if>>
								${s.name}
			                </option>
		                </#list>
		           </select>
		        </div>
		     </div>
		     <div class="column">
		        <label for="filter_EQS_parent.id">
					所属父类:
		        </label>
		        <div class="field">
		        	<select class="selection" name="filter_EQS_parent.id" id="filter_EQS_parent.id" size="25">
		        		<option value="">
							无
		                </option>
		           		<#list groupsList as gl>
			           		<option value="${gl.id}" <#if RequestParameters['filter_EQS_parent.id']?has_content && RequestParameters['filter_EQS_parent.id'] == gl.id >selected="selected"</#if> >
								${gl.name}
			                </option>
		           		</#list>
		           </select>
		        </div>
		    </div>
		</form>
		<div class="clear">
			<a href="javascript:$.form.resetForm('#search_form')" title="清空表单"><span class="button right">重 置</span></a>
			<a href="javascript:search();" title="查询输入信息"><span class="button right">查 询</span></a>
		</div>
	</div>
	<div class="panel_footer">
		<@shiro.hasPermission name="group:save">
			<a href="account/group/read" icon="group24_icon" width="610" target="dialog" dialogId="edit_group" modal="true" title="添加组">
				<span class="button left">添 加</span>
			</a>
		</@shiro.hasPermission>
		<@shiro.hasPermission name="group:delete">
	    	<a href="javascript:$.form.submitMaskForm('#delete_form',{maskEl:'#group_panel',target:'#main_content',promptMsg:'确定要删除吗?'})" title="删除选中组">
	    		<span class="button left">删 除</span>
	    	</a>
	    </@shiro.hasPermission>
	    <a href="#search_group_dailog" width="320" icon="group24_icon" target="dialog" dialogId="search_dailog" title="查询组列表">
	    	<span class="button left">查 询</span>
	    </a>
	    <#if page.totalElements gt 0>
			<div class="panel_pagging">
			    <div class="page_bar">
			    	<a href="javascript:search(0)">
				        	首页
				    </a>
			    	<#if page.hasPreviousPage()>
				        <a href="javascript:search(${page.number - 1})">
				        	上一页
				        </a>
			        </#if>
			        <#if page.hasNextPage()>
				        <a href="javascript:search(${page.number + 1})">
				        	下一页
				        </a>
				        <a href="javascript:search(${page.totalPages - 1})">
				        	尾页
				        </a>
			        </#if>
			   </div>
		    </div>
	    </#if>
	</div>
	<div class="panel_content">
  	  <#if message?has_content>
	  	  <div class="notification information">
	  	  	<a href="#" class="close"><img src="resources/images/icons/16/close.png" title="关闭信息" alt="关闭"></a>
	  	  	${message}
	  	  </div>
  	  </#if>
	  <form id="delete_form" action="account/group/delete" method="post">
		  <table width="100%" id="group_list">
		    	<thead>
		        	<tr>
		        		<th>
		        			<div style="width:15px;height:15px;margin:0 auto;">
		        				<input type="checkbox" id="selectAll" class="checker"/>
		        			</div>
		        		</th>
		            	<th>
		                	组名称
		            	</th>
		                <th>
		                	状态
		            	</th>
		                <th>
		                	所属父类
		            	</th>
		            	<th>
		            		备注
		            	</th>
		            	<th>
		            		操作
		            	</th>
		            </tr>
		        </thead>
		        <tbody>
		        	<#list page.content as e>
		            	<tr>
		            		<td>
		            			<div style="width:15px;height:15px;margin:0 auto;">
		            				<input type="checkbox" name="ids" value="${e.id}" class="checker"/>
		            			</div>
		            		</td>
		                	<td>
		                    	${e.name!""}
		                    </td>
		                    <td>
		                    	${e.stateName!""}
		                    </td>
		                    <td>
		                    	${e.parentName!""}
		                    </td>
		                    <td>
		                    	${e.remark!""}
		                    </td>
		                    <td align="center">
		                    	<@shiro.hasPermission name="group:read">
		                    		<a href="account/group/read?id=${e.id}" icon="group24_icon"  width="610" target="dialog" dialogId="edit_group" modal="true" title="修改组/${e.name}" class="operat edit16_icon">
		                    	</@shiro.hasPermission>
		                    </td>
		                </tr>
		            </#list>
		        </tbody>
		    </table>
		</form>
	</div>
	<#if page.totalElements gt 0>
		<div class="panel_pagging2">
		 	<div class="page_bar2">
		    	 共有${page.totalPages}页/${page.totalElements}条记录
		    </div>
		 </div>
	</#if>
</div>